name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint (all projects)
        env:
          HUSKY: 0
        run: npx nx run-many -t lint --all --parallel=3 || echo "No lint targets"

      - name: Format check
        env:
          HUSKY: 0
        run: npm run format:check

      - name: Build (affected or all)
        if: ${{ github.event_name == 'push' }}
        env:
          HUSKY: 0
        run: |
          npx nx affected -t build --parallel=3 --base=origin/master~1 --head=HEAD || \
          npx nx run-many -t build --all --parallel=3 || echo "No build targets"

      - name: Cache Nx
        uses: actions/cache@v4
        with:
          path: .nx/cache
          key: nx-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            nx-${{ runner.os }}-

      - name: Unit tests (if exist)
        run: |
          npx nx show projects --type=lib >/dev/null 2>&1 || echo "No libs"
          # Placeholder for tests. Add: npx nx affected -t test --base=origin/master~1 --head=HEAD
          echo "(No test target configured yet)"
